name: Playwright Table Sum

on:
  push:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Node Modules
      run: npm install

    - name: Install Playwright Browsers
      run: npx --yes playwright install chromium

    - name: Run Scraper 24f3003295@ds.study.iitm.ac.in
      run: node scrape.js
